import mongoose from 'mongoose'
import bcrypt from 'bcrypt'
import { ObjectId } from 'mongodb';


// Stores fraud alerts generated by the system.
const alertSchema = mongoose.Schema({
      user:{
            type:ObjectId,
            ref: 'user'
      },
      transaction:{
            type:ObjectId,
            ref: 'transaction'
      },
      alert_type:{ // "fraud", "suspicious_login"
            type:String,
      },
    message:{
            type:String,
      },

      regDate:{
            type:String,
      },
      
})


const Alert = mongoose.model('alert',alertSchema)
export default Alert;